#!/usr/bin/env bun
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import matter from 'gray-matter'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const rootDir = path.resolve(__dirname, '..')
const projectsDir = path.resolve(rootDir, 'projects')
const outDir = path.resolve(rootDir, 'src', 'data', 'generated')
const outFile = path.resolve(outDir, 'projects.ts')

async function ensureDir(dir: string) {
  await fs.mkdir(dir, { recursive: true })
}

function sanitizeMeta(meta: any, id: string) {
  const title = typeof meta?.title === 'string' ? meta.title : id
  const tagline = typeof meta?.tagline === 'string' ? meta.tagline : ''
  const tags = Array.isArray(meta?.tags)
    ? meta.tags.filter((t) => typeof t === 'string')
    : undefined
  return { id, title, tagline, tags }
}

async function generate() {
  try {
    const entries = await fs.readdir(projectsDir, { withFileTypes: true })
    const mdFiles = entries
      .filter((e) => e.isFile() && e.name.endsWith('.md'))
      .map((e) => e.name)

    const index: Array<{ id: string; title: string; tagline: string; tags?: string[] }> = []

    for (const file of mdFiles) {
      const id = file.replace(/\.md$/, '')
      const fullPath = path.join(projectsDir, file)
      const raw = await fs.readFile(fullPath, 'utf8')
      const { data } = matter(raw)
      const meta = sanitizeMeta(data, id)
      index.push(meta)
    }

    // Sort by title for stable ordering
    index.sort((a, b) => a.title.localeCompare(b.title))

    const header = `// This file is auto-generated by scripts/generate-projects.ts. Do not edit.\n// Generated at ${new Date().toISOString()}\n`

    const typeDef = `export type ProjectMeta = { id: string; title: string; tagline: string; tags?: string[] };`

    const indexLiteral = JSON.stringify(index, null, 2)

    const fileContents = [
      header,
      typeDef,
      `\nexport const projectsIndex: ProjectMeta[] = ${indexLiteral} as const;`,
      `\nexport function getProjectById(id: string) {\n  return projectsIndex.find((p) => p.id === id) ?? null\n}`,
      '\n',
    ].join('\n')

    await ensureDir(outDir)
    await fs.writeFile(outFile, fileContents, 'utf8')

    console.log(
      `Generated ${path.relative(rootDir, outFile)} with ${index.length} project(s).`
    )
  } catch (err) {
    console.error('Failed to generate projects:', err)
    process.exitCode = 1
  }
}

await generate()
